### ISSUE TITLE
the node hangs in "try to send" state

### ISSUE THREAD

**Issue by appzer** [FreeTimeCoder82/node-red-contrib-pushsafer#4]
### reported by a Pushsafer user:

I am using pushsafer withing my node-red since a quite long time. Never had any problems.
Lately I realised, that notifications are not coming. Reviewing my node-red I realised,
that every time a notification is activated, the node hangs in "try to send" state,
and node-red exist and restarts.

This is what I see in node-red logs:

Cannot parse error: {"reason":"Unregistered","timestamp":1670594516475}{"status":1,"success":"message transmitted","available":2199,"message_ids":"28405336:15742"}
11 Dec 13:07:08 - [red] Uncaught Exception:
11 Dec 13:07:08 - [error] SyntaxError: Unexpected token { in JSON at position 51
at JSON.parse (<anonymous>)
at /home/pi/.node-red/node_modules/node-red-pushsafer/pushsafer/pushsafer.js:151:45
at IncomingMessage.<anonymous> (/home/pi/.node-red/node_modules/pushsafer-notifications/lib/pushsafer.js:78:6)
at IncomingMessage.emit (events.js:412:35)
at endReadableNT (internal/streams/readable.js:1334:12)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Consumed 17min 24.908s CPU time.

**Comment by coxifred** [comment]
Hi, same issue here

Possible to fix ?

Thanks
